### ISSUE TITLE
Can't find SimConnect.dll

### ISSUE THREAD

**Issue by CyrilPaulus** [lian/msfs2020-go#1]
I have to following error when trying to launch vfrmap.exe

`panic: Failed to load D:\SimConnect.dll: The specified module could not be found.

goroutine 1 [running]:
main.main()
        /users/lian/prj/go/lian/msfs2020-go/vfrmap/main.go:76 +0x88b`

**Comment by Raging-Beard** [comment]
Strange, for me when I run the exe, SimConnect.dll is created. That is to say, vfrmap.exe is the only file in the folder, upon running it, SimConnect.dll then also appears in the folder.

**Comment by lian** [comment]
yea, vfrmap.exe looks for SimConnect.dll in your current folder, and otherwise auto creates it. my only guess for your issue might be a permission issue on your `D:\` top level folder and doesn't allow vfrmap.exe to auto create SimConnect.dll.

try to move the vfrmap.exe to a different folder. maybe for a test simply to your desktop folder.

**Comment by CyrilPaulus** [comment]
When I run vfrmap.exe I see that the SimConnect.dll is created but I still have this message.

I tried in different folder and they all have the correct access rights.
I tried running it with an admin cmd, and still it won't work.

**Comment by lian** [comment]
@CyrilPaulus sorry, i'm unable to reproduce this. and don't have enough windows knowledge how best to debug this. have you tried on your `C:` disk?

please report back if you figure out this issue, or maybe someone else does.
