### ISSUE TITLE
It loads but says "This page can't load Google Maps correctly"

### ISSUE THREAD

**Issue by Raging-Beard** [lian/msfs2020-go#5]
The map is dark and has "For development purposes only" written all over it.

**Comment by Raging-Beard** [comment]
Hmm, maybe not an issue my end as randomly now worked.

**Comment by Raging-Beard** [comment]
Now getting it again GRRRRR

**Comment by krobertson** [comment]
@Raging-Beard Lian asked me to follow up, he is currently on the road and not able to respond. It looks like the popularity of the plugin used up his Google Maps quota. He will look at increasing the quota when he gets home and is able to look into it.

**Comment by Raging-Beard** [comment]
Oh I see, thank you for getting back to me. Well worst case we can still use it, kind of, but not as well lol. Cheers.

**Comment by neoteknic** [comment]
Same problem, maybe a way to enter a custom api key? Maybe add OSM too to have the choice of multiple map providers ?

**Comment by mk0x9** [comment]
Ability to set own google maps API key would be nice

**Comment by krobertson** [comment]
When you run it, simply add `-api-key` with your own key. This is noted in the command's readme: https://github.com/lian/msfs2020-go/tree/master/vfrmap#arguments

**Comment by lian** [comment]
@krobertson :love_letter: thank you!

i increased the daily usage limit FOR NOW. but its high enough that i would have to pay real money to google for using google maps at the end of the month, and don't want that for an open source project :joy: 

you already can set your own api key using `-api-key <your-key` as a command. ([how-to-set-arguments-on-windows](https://www.digitalcitizen.life/shortcut-arguments-parameters-windows))

but most users probably don't want to create their own gmap api key.

tomorrow i will hunt for a sponsor that provides a higher limit api-key, or otherwise will release v0.0.3 with openstreetmap support. maybe keep gmap but if it rans out of daily limits then users can at least use openstreetmap.

**Comment by lian** [comment]
released v0.0.3 https://github.com/lian/msfs2020-go/releases/tag/v0.0.3

had to switch to openstreetmap
