### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by singularcitrus** [lian/msfs2020-go#7]
Hi, I would like to contribute, but I'm not too familiar with go.
Can you maybe update the readme on how to build the app?
I would really appreciate that

**Comment by judaihyun** [comment]
> Hi, I would like to contribute, but I'm not too familiar with go.
> Can you maybe update the readme on how to build the app?
> I would really appreciate that


i agree too.
if js or cpp or .... i can contribute haha

http://www.prepar3d.com/SDKv2/LearningCenter/simobjects/simobject_api_getting_started.html

**Comment by lian** [comment]
i can extend the already existing section here https://github.com/lian/msfs2020-go/tree/master/vfrmap#compile

not sure yet how deep i want to go. if you have golang installed, and downloaded or git cloned this repository and are its folder, `go build github.com/lian/msfs2020-go/vfrmap` should just work. no need to install anything else apart from go. no dotnet no nothing.

then follow https://github.com/lian/msfs2020-go/tree/master/vfrmap#change-visualisation to copy the index.html in the same folder as the exe. because go build won't bake that into the exe. `go generate github.com/lian/msfs2020-go/vfrmap` does that but for that you need go-bindata installed, but its not needed if the index.html is inside the same folder, the app then just uses that.

i personally write and build the app on linux and then just copy the built exe to my gaming windows pc.

**Comment by singularcitrus** [comment]
I didn't realize there was another readme in the vfrmap subfolder. I also prefer coding on linux, but I usually just use windows when I'm working on windows apps
